; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\tom.giglia\AppData\Local\Temp\.NETFramework,Version=v4.7.AssemblyAttributes.cpp"
